### ISSUE TITLE
TypeError on localhost:3000

### ISSUE THREAD

**Issue by alex-rieger** [JeremiasEh/base-class#2]
# reproduction
* clone the project
* run ```npm i```
* run ```node index.js```
* go to ```localhost:3000```

# console output:
```
Server listening on Port: 3000
Error: TypeError: this.Repeat is not a function
    at InputLabel.get template [as template] (src/components/input-label.js:15:20)
    at InputLabel.render (/Users/user/Sites/base-class/scripts/ssr-base-element.js:53:43)
    at ComponentRenderer.componentHTML (/Users/user/Sites/base-class/scripts/server/component-renderer.js:68:47)
    at Function._replaceComponentTags (/Users/user/Sites/base-class/scripts/server/html-converter.js:135:52)
    at componentNames.forEach.componentName (/Users/user/Sites/base-class/scripts/server/html-converter.js:31:56)
    at Array.forEach (<anonymous>)
    at Promise (/Users/user/Sites/base-class/scripts/server/html-converter.js:30:28)
    at new Promise (<anonymous>)
    at HTMLConverter.exportHTML (/Users/user/Sites/base-class/scripts/server/html-converter.js:23:16)
    at app.get (/Users/user/Sites/base-class/index.js:37:19)
(node:32359) UnhandledPromiseRejectionWarning: ReferenceError: pagesDir is not defined
    at htmlConverter.exportHTML.then.catch.error (/Users/user/Sites/base-class/index.js:44:52)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:32359) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:32359) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by alex-rieger** [comment]
```
node -v: v10.13.0
npm -v: 6.4.1
```

**Comment by tangleMesh** [comment]
#5  is fixed now!
